// Generated by Wrangler on Tue Sep 24 2024 16:28:37 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	FIREBASE_API_KEY: string;
	FIREBASE_AUTH_DOMAIN: string;
	FIREBASE_PROJECT_ID: string;
	FIREBASE_STORAGE_BUCKET: string;
	FIREBASE_MESSAGING_SENDER_ID: string;
	FIREBASE_APP_ID: string;
	FIREBASE_RECAPTCHA_SITE_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_ANALYTICS_ID: string;
	PUBLIC_URL: string;
}
