// Generated by Wrangler on Tue Sep 24 2024 17:54:44 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	FIREBASE_AUTH_DOMAIN: "felesvlinder-7e64a.firebaseapp.com";
	FIREBASE_PROJECT_ID: "felesvlinder-7e64a";
	FIREBASE_STORAGE_BUCKET: "felesvlinder-7e64a.appspot.com";
	FIREBASE_MESSAGING_SENDER_ID: "815094624385";
	FIREBASE_APP_ID: "1:815094624385:web:5907fbc21441be7360dd80";
	FIREBASE_RECAPTCHA_SITE_KEY: "6LeEvxwpAAAAAEGWOBfQPcjNQ7WJsiuBcEjnqXm5";
	GOOGLE_ANALYTICS_ID: "G-56X1T5C2Y3";
	PUBLIC_URL: "https://felesvlinder.com";
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	FIREBASE_API_KEY: string;
}
